import { ReactNode } from 'react'
import './globals.css'
import { Raleway } from 'next/font/google'

const raleway = Raleway({ weight: '300', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  )
}
