import { ReactNode } from 'react'
import './globals.css'
import { IBM_Plex_Sans as ibmPlexSans } from 'next/font/google'
import { Header } from '@/components/header/Header'
import { FormContextProvider } from '@/context/formContext'

const plex = ibmPlexSans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--ibm',
})

export const metadata = {
  title: 'Fomulário Multi Step',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={plex.className}>
        <div className="flex h-screen w-screen items-center justify-center">
          <div className="flex w-1/2 flex-col rounded-md border border-gray-100 bg-white p-8">
            <FormContextProvider>
              <Header />
              {children}
            </FormContextProvider>
          </div>
        </div>
      </body>
    </html>
  )
}
